---
# key-value mapping of actor-leak site URL
sites:
  conti: http://something.onion
  revil: http://something.onion
  avaddon: http://something.onion
  darkside: http://something.onion

# slack webhooks
slack:
  workspace1: 
    # url for the webhook
    url: https://hooks.slack.com/services/something/goes/here

    # should notifications be sent to this webhook if a site is detected as down?
    down_sites: true

    # should errors be sent to this webook?
    errors: true

    # may in the future add support for not sending leak site links
    # if you actively want this, open an issue (or make a PR)
  workspace2:
    url: https://hooks.slack.com/services/something/else/goes/here
    down_sites: true
    errors: false

# how many seconds to wait for a connection
# this is used to check if the site is up, and doesn't wait
# for the full page data to be downloaded
timeout: 30

# tor proxy settings
# the values set below are for the provided docker-compose.yml/Dockerfile.proxy
# adjust for your own custom environment
proxy:
  # hostname for the proxy
  hostname: proxy

  # port for the SOCKS proxy
  socks_port: 9050

  # port for the tor control service
  control_port: 9051

  # password for the tor control service
  password: password