version: "3.9"

services:
  app:
    build: .
    depends_on:
      - proxy
    volumes:
      - ./db_vol:/db
    environment:
      PYTHONUNBUFFERED: 1
      RW_DB_PATH: /db/ransomwatch.db

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
